apiVersion: kubeadm.k8s.io/v1beta3
kind: InitConfiguration

localAPIEndpoint:
  advertiseAddress: 100.64.0.4
  bindPort: 6443

nodeRegistration:
  name: k8s-master
  criSocket: unix:///var/run/cri-dockerd.sock

---
apiVersion: kubeadm.k8s.io/v1beta3
kind: ClusterConfiguration

kubernetesVersion: v1.28.15

imageRepository: crpi-ckw9ia686aku4y4w.cn-shanghai.personal.cr.aliyuncs.com/tgtech

networking:
  podSubnet: 10.0.0.0/16
  serviceSubnet: 10.96.0.0/12

